"""add cinema_showtimes and traffic_cache tables

Revision ID: 22fbd3a7c45e
Revises: f1a2b3c4d5e6
Create Date: 2026-02-17 22:48:10.224578

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

revision = '22fbd3a7c45e'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema_showtimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cinema_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('showtimes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('poster_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cinema_date_title', 'cinema_showtimes', ['cinema_name', 'date', 'title'], unique=False)
    op.create_index(op.f('ix_cinema_showtimes_cinema_name'), 'cinema_showtimes', ['cinema_name'], unique=False)
    op.create_index(op.f('ix_cinema_showtimes_date'), 'cinema_showtimes', ['date'], unique=False)
    op.create_index(op.f('ix_cinema_showtimes_fetched_at'), 'cinema_showtimes', ['fetched_at'], unique=False)
    op.create_table('traffic_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_cache_fetched_at'), 'traffic_cache', ['fetched_at'], unique=False)
    # op.drop_table('layer')  # SKIP: PostGIS topology table
    # op.drop_table('tract', schema='tiger')  # SKIP: PostGIS TIGER table
    op.drop_index('idx_gus_category_year', table_name='gus_statistics')
    op.drop_index('ix_gus_statistics_category', table_name='gus_statistics')
    op.drop_index('ix_gus_statistics_year', table_name='gus_statistics')
    op.drop_table('gus_statistics')  # OK: Legacy model - safe to drop
    # op.drop_table('layer', schema='topology')  # SKIP: PostGIS topology table
    # op.drop_table('tract')  # SKIP: PostGIS TIGER table
    op.drop_constraint('gus_data_refresh_log_var_key_key', 'gus_data_refresh_log', type_='unique')
    op.create_index(op.f('ix_gus_data_refresh_log_var_key'), 'gus_data_refresh_log', ['var_key'], unique=True)
    op.alter_column('gus_gmina_stats', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('gus_insights', 'data_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_gus_insights_category'), 'gus_insights', ['category'], unique=False)
    op.drop_index('idx_gus_avg_level', table_name='gus_national_averages')
    op.drop_index('idx_gus_avg_var_id', table_name='gus_national_averages')
    op.drop_index('idx_gus_avg_var_key', table_name='gus_national_averages')
    op.drop_index('idx_gus_avg_year', table_name='gus_national_averages')
    op.create_index(op.f('ix_gus_national_averages_level'), 'gus_national_averages', ['level'], unique=False)
    op.create_index(op.f('ix_gus_national_averages_var_id'), 'gus_national_averages', ['var_id'], unique=False)
    op.create_index(op.f('ix_gus_national_averages_var_key'), 'gus_national_averages', ['var_key'], unique=False)
    op.create_index(op.f('ix_gus_national_averages_year'), 'gus_national_averages', ['year'], unique=False)
    op.alter_column('reports', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('reports', 'ai_summary',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index('idx_reports_category', table_name='reports')
    op.drop_index('idx_reports_created_at', table_name='reports')
    op.drop_index('idx_reports_status', table_name='reports')
    op.drop_index('idx_reports_user_id', table_name='reports')
    op.create_index(op.f('ix_reports_category'), 'reports', ['category'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_category'), table_name='reports')
    op.create_index('idx_reports_user_id', 'reports', ['user_id'], unique=False)
    op.create_index('idx_reports_status', 'reports', ['status'], unique=False)
    op.create_index('idx_reports_created_at', 'reports', ['created_at'], unique=False)
    op.create_index('idx_reports_category', 'reports', ['category'], unique=False)
    op.alter_column('reports', 'ai_summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reports', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_gus_national_averages_year'), table_name='gus_national_averages')
    op.drop_index(op.f('ix_gus_national_averages_var_key'), table_name='gus_national_averages')
    op.drop_index(op.f('ix_gus_national_averages_var_id'), table_name='gus_national_averages')
    op.drop_index(op.f('ix_gus_national_averages_level'), table_name='gus_national_averages')
    op.create_index('idx_gus_avg_year', 'gus_national_averages', ['year'], unique=False)
    op.create_index('idx_gus_avg_var_key', 'gus_national_averages', ['var_key'], unique=False)
    op.create_index('idx_gus_avg_var_id', 'gus_national_averages', ['var_id'], unique=False)
    op.create_index('idx_gus_avg_level', 'gus_national_averages', ['level'], unique=False)
    op.drop_index(op.f('ix_gus_insights_category'), table_name='gus_insights')
    op.alter_column('gus_insights', 'data_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('gus_gmina_stats', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_gus_data_refresh_log_var_key'), table_name='gus_data_refresh_log')
    op.create_unique_constraint('gus_data_refresh_log_var_key_key', 'gus_data_refresh_log', ['var_key'], postgresql_nulls_not_distinct=False)
    op.create_table('tract',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('countyfp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('tractce', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('tract_id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('namelsad', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('funcstat', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('aland', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('awater', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intptlat', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('intptlon', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('the_geom', sa.NullType(), autoincrement=False, nullable=True),
    sa.CheckConstraint("geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL", name='enforce_geotype_geom'),
    sa.CheckConstraint('st_ndims(the_geom) = 2', name='enforce_dims_geom'),
    sa.CheckConstraint('st_srid(the_geom) = 4269', name='enforce_srid_geom'),
    sa.PrimaryKeyConstraint('tract_id', name='tract_pkey')
    )
    op.create_table('layer',
    sa.Column('topology_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('layer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_column', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topology_id'], ['topology.topology.id'], name='layer_topology_id_fkey'),
    sa.PrimaryKeyConstraint('topology_id', 'layer_id', name='layer_pkey'),
    sa.UniqueConstraint('schema_name', 'table_name', 'feature_column', name='layer_schema_name_table_name_feature_column_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='topology'
    )
    op.create_table('gus_statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fetched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('population_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unemployment_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gus_statistics_pkey')
    )
    op.create_index('ix_gus_statistics_year', 'gus_statistics', ['year'], unique=False)
    op.create_index('ix_gus_statistics_category', 'gus_statistics', ['category'], unique=False)
    op.create_index('idx_gus_category_year', 'gus_statistics', ['category', 'year'], unique=True)
    op.create_table('tract',
    sa.Column('gid', sa.INTEGER(), server_default=sa.text('nextval(\'"tiger".tract_gid_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('countyfp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('tractce', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('tract_id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('namelsad', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('funcstat', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('aland', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('awater', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intptlat', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('intptlon', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('the_geom', sa.NullType(), autoincrement=False, nullable=True),
    sa.CheckConstraint("geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL", name='enforce_geotype_geom'),
    sa.CheckConstraint('st_ndims(the_geom) = 2', name='enforce_dims_geom'),
    sa.CheckConstraint('st_srid(the_geom) = 4269', name='enforce_srid_geom'),
    sa.PrimaryKeyConstraint('tract_id', name='tract_pkey'),
    schema='tiger'
    )
    op.create_table('layer',
    sa.Column('topology_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('layer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_column', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topology_id'], ['topology.id'], name='layer_topology_id_fkey'),
    sa.PrimaryKeyConstraint('topology_id', 'layer_id', name='layer_pkey'),
    sa.UniqueConstraint('schema_name', 'table_name', 'feature_column', name='layer_schema_name_table_name_feature_column_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_traffic_cache_fetched_at'), table_name='traffic_cache')
    op.drop_table('traffic_cache')
    op.drop_index(op.f('ix_cinema_showtimes_fetched_at'), table_name='cinema_showtimes')
    op.drop_index(op.f('ix_cinema_showtimes_date'), table_name='cinema_showtimes')
    op.drop_index(op.f('ix_cinema_showtimes_cinema_name'), table_name='cinema_showtimes')
    op.drop_index('idx_cinema_date_title', table_name='cinema_showtimes')
    op.drop_table('cinema_showtimes')
    # ### end Alembic commands ###
