"""Add weather table

Revision ID: 4c3da584f838
Revises: eaf850ae92d0
Create Date: 2026-01-08 14:03:41.626333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4c3da584f838'
down_revision = 'eaf850ae92d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('feels_like', sa.Float(), nullable=False),
    sa.Column('temp_min', sa.Float(), nullable=False),
    sa.Column('temp_max', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('main', sa.String(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=False),
    sa.Column('pressure', sa.Integer(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('wind_deg', sa.Integer(), nullable=True),
    sa.Column('clouds', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Integer(), nullable=True),
    sa.Column('rain_1h', sa.Float(), nullable=True),
    sa.Column('rain_3h', sa.Float(), nullable=True),
    sa.Column('sunrise', sa.DateTime(), nullable=True),
    sa.Column('sunset', sa.DateTime(), nullable=True),
    sa.Column('forecast', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_fetched_at'), 'weather', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_weather_location'), 'weather', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_location'), table_name='weather')
    op.drop_index(op.f('ix_weather_fetched_at'), table_name='weather')
    op.drop_table('weather')
    # ### end Alembic commands ###
