"""Add AirQuality table

Revision ID: 70f98d07849e
Revises: b2c3d4e5f6a7
Create Date: 2026-02-03 20:58:46.374416

"""
import sqlmodel
from alembic import op
import sqlalchemy as sa


revision = '70f98d07849e'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pm25', sa.Float(), nullable=False),
    sa.Column('pm10', sa.Float(), nullable=False),
    sa.Column('caqi', sa.Float(), nullable=False),
    sa.Column('caqi_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_air_quality_fetched_at'), 'air_quality', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_air_quality_location'), 'air_quality', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_air_quality_location'), table_name='air_quality')
    op.drop_index(op.f('ix_air_quality_fetched_at'), table_name='air_quality')
    op.drop_table('air_quality')
    # ### end Alembic commands ###
