"""Add detailed CEIDG fields

Revision ID: 71cfcbfd9588
Revises: a7d27cd6a965
Create Date: 2026-02-05 17:00:13.760021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

revision = '71cfcbfd9588'
down_revision = 'a7d27cd6a965'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skipped PostGIS drop tables
    op.add_column('ceidg_businesses', sa.Column('adres_korespondencyjny', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ceidg_businesses', sa.Column('spolki', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ceidg_businesses', sa.Column('obywatelstwa', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ceidg_businesses', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ceidg_businesses', sa.Column('www', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ceidg_businesses', sa.Column('telefon', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ceidg_businesses', 'telefon')
    op.drop_column('ceidg_businesses', 'www')
    op.drop_column('ceidg_businesses', 'email')
    op.drop_column('ceidg_businesses', 'obywatelstwa')
    op.drop_column('ceidg_businesses', 'spolki')
    op.drop_column('ceidg_businesses', 'adres_korespondencyjny')
    # Skipped PostGIS create tables
    # ### end Alembic commands ###
