"""Add PKD fields

Revision ID: a7d27cd6a965
Revises: c3e1d9a4b5f7
Create Date: 2026-02-05 16:46:50.470480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

revision = 'a7d27cd6a965'
down_revision = 'c3e1d9a4b5f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('layer') - Skipped (PostGIS)
    # op.drop_table('tract') - Skipped (PostGIS)
    # op.drop_table('layer', schema='topology') - Skipped (PostGIS)
    # op.drop_table('tract', schema='tiger') - Skipped (PostGIS)
    op.drop_index('ix_articles_category', table_name='articles')
    op.drop_index('ix_articles_processed', table_name='articles')
    op.drop_index('ix_articles_published_at', table_name='articles')
    op.add_column('ceidg_businesses', sa.Column('pkd_main', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ceidg_businesses', sa.Column('pkd_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_ceidg_businesses_miasto'), 'ceidg_businesses', ['miasto'], unique=False)
    op.create_index(op.f('ix_ceidg_businesses_nip'), 'ceidg_businesses', ['nip'], unique=False)
    op.create_index(op.f('ix_ceidg_businesses_pkd_main'), 'ceidg_businesses', ['pkd_main'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ceidg_businesses_pkd_main'), table_name='ceidg_businesses')
    op.drop_index(op.f('ix_ceidg_businesses_nip'), table_name='ceidg_businesses')
    op.drop_index(op.f('ix_ceidg_businesses_miasto'), table_name='ceidg_businesses')
    op.drop_column('ceidg_businesses', 'pkd_list')
    op.drop_column('ceidg_businesses', 'pkd_main')
    op.create_index('ix_articles_published_at', 'articles', ['published_at'], unique=False)
    op.create_index('ix_articles_processed', 'articles', ['processed'], unique=False)
    op.create_index('ix_articles_category', 'articles', ['category'], unique=False)
    # PostGIS tables skipped in upgrade, so skipped in downgrade
    # ### end Alembic commands ###
    # ### end Alembic commands ###
